# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
#
name: Test docker multiarch build

# Trigger the workflow's on all PRs and pushes so that other contributors can
# run tests in their own forks. Avoid triggering these tests on changes to
# changes not influencing the images.
on:
  pull_request:
    paths:
      - "images/**"
      - "chartpress.yaml"
      - ".github/workflows/test-docker-build.yaml"
  push:
    paths:
      - "images/**"
      - "chartpress.yaml"
      - ".github/workflows/test-docker-build.yaml"
    branches-ignore:
      - "dependabot/**"
  workflow_dispatch:

jobs:
  # This is a quick test to check the arm64 docker images based on:
  # - https://github.com/docker/build-push-action/blob/v2.3.0/docs/advanced/local-registry.md
  # - https://github.com/docker/build-push-action/blob/v2.3.0/docs/advanced/multi-platform.md
  build_images:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install chartpress
        run: |
          # FIXME: six is required by docker 5.0.0 but isn't explicitly required
          #        https://github.com/docker/docker-py/issues/2807
          #
          pip install chartpress six

      - name: Set up QEMU (for docker buildx)
        uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480 # dependabot updates to latest release

      - name: Set up Docker Buildx (for chartpress multi-arch builds)
        uses: docker/setup-buildx-action@0d135e0c2fc0dba0729c1a47ecfcf5a3c7f8579e # dependabot updates to latest release

      - name: Build a multiple architecture Docker image
        run: >-
          chartpress
          --builder docker-buildx
          --platform linux/amd64 --platform linux/arm64
